addons:
  sonarcloud:
    organization: "cordeiro21"
    token:
      secure: "d4jB9nkVWwUrMXtCsPLo5YEa6Z0Dyye+v51amwqqlpXn7enJ7nkJ0AVHBINj/j3KdMgUm9oU9+35o4PvQ2/maIJ95xbRVICINjhTGCtmpvFRXtCq9fLlsLV2eEeqGA1RAfrja1y8M0SCd8L+igXPaGTVZDw0wtcOG3BABA7knmClSLj1YtQw9bln5FLoR53J/OvSQ6I3rN/ht3jRIK7aBQ5MeL2c5K1IEsjsWVlvF0XEukvfA5oFyvynLDzEwtZobgoMzS/+AHk/eA3k7xNU2Ey/9OOHeoMuuWpNhpjTOL5ceYBo7b4O0P0GT8iHsePwuzZzUwD5GrxTUijaixqUpqZAe5eHuhDqZ6h8GWWAEP0fgEgcdXBqrdEzhxN7fLhnGML33wM+YXHlST9hH7i1ADJU3IqzlhGmDDFozInIr+2AjMKtvdN4vI4SQYaFXNBhd24a8RoyLPgGAjry028SJ7DDEzXOb6uaN+PcFF8iTyP6ErdY+vs5YGynuYwirv9Te7EF+6/gYx3oHANgGpmgV8TT0UI/VhbynF0Iu+uZehAwrs1wXDZv6kipUlG0Ok2/b4mTy2igvYyhaGT6KKTCH7U/H360h4vfGKtq9xEGFIDqxEzQ1cxhM0pcwQgeIl7cVLDRdsoOJW4UUvG3hJPKEBSs13lFMhl/CSWtF6mCDFM=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cordeiro21_cliente_8





#addons:
 # sonarcloud:
  #  organization: "cordeiro21"
   # token:
    #  secure: d4jB9nkVWwUrMXtCsPLo5YEa6Z0Dyye+v51amwqqlpXn7enJ7nkJ0AVHBINj/j3KdMgUm9oU9+35o4PvQ2/maIJ95xbRVICINjhTGCtmpvFRXtCq9fLlsLV2eEeqGA1RAfrja1y8M0SCd8L+igXPaGTVZDw0wtcOG3BABA7knmClSLj1YtQw9bln5FLoR53J/OvSQ6I3rN/ht3jRIK7aBQ5MeL2c5K1IEsjsWVlvF0XEukvfA5oFyvynLDzEwtZobgoMzS/+AHk/eA3k7xNU2Ey/9OOHeoMuuWpNhpjTOL5ceYBo7b4O0P0GT8iHsePwuzZzUwD5GrxTUijaixqUpqZAe5eHuhDqZ6h8GWWAEP0fgEgcdXBqrdEzhxN7fLhnGML33wM+YXHlST9hH7i1ADJU3IqzlhGmDDFozInIr+2AjMKtvdN4vI4SQYaFXNBhd24a8RoyLPgGAjry028SJ7DDEzXOb6uaN+PcFF8iTyP6ErdY+vs5YGynuYwirv9Te7EF+6/gYx3oHANgGpmgV8TT0UI/VhbynF0Iu+uZehAwrs1wXDZv6kipUlG0Ok2/b4mTy2igvYyhaGT6KKTCH7U/H360h4vfGKtq9xEGFIDqxEzQ1cxhM0pcwQgeIl7cVLDRdsoOJW4UUvG3hJPKEBSs13lFMhl/CSWtF6mCDFM= encrypted value of your token

#script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cordeiro21_cliente_8
 # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
#env:
# global:
#    secure: d4jB9nkVWwUrMXtCsPLo5YEa6Z0Dyye+v51amwqqlpXn7enJ7nkJ0AVHBINj/j3KdMgUm9oU9+35o4PvQ2/maIJ95xbRVICINjhTGCtmpvFRXtCq9fLlsLV2eEeqGA1RAfrja1y8M0SCd8L+igXPaGTVZDw0wtcOG3BABA7knmClSLj1YtQw9bln5FLoR53J/OvSQ6I3rN/ht3jRIK7aBQ5MeL2c5K1IEsjsWVlvF0XEukvfA5oFyvynLDzEwtZobgoMzS/+AHk/eA3k7xNU2Ey/9OOHeoMuuWpNhpjTOL5ceYBo7b4O0P0GT8iHsePwuzZzUwD5GrxTUijaixqUpqZAe5eHuhDqZ6h8GWWAEP0fgEgcdXBqrdEzhxN7fLhnGML33wM+YXHlST9hH7i1ADJU3IqzlhGmDDFozInIr+2AjMKtvdN4vI4SQYaFXNBhd24a8RoyLPgGAjry028SJ7DDEzXOb6uaN+PcFF8iTyP6ErdY+vs5YGynuYwirv9Te7EF+6/gYx3oHANgGpmgV8TT0UI/VhbynF0Iu+uZehAwrs1wXDZv6kipUlG0Ok2/b4mTy2igvYyhaGT6KKTCH7U/H360h4vfGKtq9xEGFIDqxEzQ1cxhM0pcwQgeIl7cVLDRdsoOJW4UUvG3hJPKEBSs13lFMhl/CSWtF6mCDFM=
